// frontend-react/src/features/mentors/components/MentorCard.tsx
import React from 'react';
import type { MentorProfile } from '../../../types/mentor';
import { useAuthStore } from '../../../store/authStore';
import { apiClient } from '../../../api/apiClient';
import './MentorCard.scss'; // Assuming we'll add the scss if needed

interface MentorCardProps {
  mentor: MentorProfile & { username?: string };
  overrideRating?: number | null;
  overrideLearnersCount?: number | null;
  onView: (id: number) => void;
  onBook: (id: number) => void;
  onChat?: (id: number) => void;
  enrichedRating?: number | null;
  enrichedReviewCount?: number | null;
}

export const MentorCard: React.FC<MentorCardProps> = ({
  mentor,
  overrideRating,
  overrideLearnersCount,
  onView,
  onBook,
  onChat,
  enrichedRating,
  enrichedReviewCount
}) => {
  const { user } = useAuthStore();
  const [localRating, setLocalRating] = React.useState<number | null>(null);
  const [localReviewCount, setLocalReviewCount] = React.useState<number | null>(null);
  const isOwnProfile = user?.userId === mentor.userId;

  React.useEffect(() => {
    // Only fetch if we haven't been provided overrides
    if (overrideRating === undefined && enrichedRating === undefined) {
      apiClient.get(`/review/mentors/${mentor.userId}/rating`)
        .then(res => {
          const data = res.data.data || res.data;
          setLocalRating(data.averageRating);
          setLocalReviewCount(data.totalReviews);
        })
        .catch(err => {
          console.warn(`Failed to enrich ratings for mentor ${mentor.userId}`, err);
        });
    }
  }, [mentor.userId, overrideRating, enrichedRating]);
  const initials = () => {
    const name = mentor.name || mentor.username || 'M';
    return name.charAt(0).toUpperCase();
  };

  const finalRating = overrideRating ?? enrichedRating ?? localRating ?? mentor.rating;
  const finalReviews = overrideLearnersCount ?? enrichedReviewCount ?? localReviewCount ?? mentor.totalStudents;

  return (
    <div 
      className="card" 
      onClick={() => onView(mentor.userId)} 
      onKeyUp={(e) => e.key === 'Enter' && onView(mentor.userId)}
      tabIndex={0} 
      role="button" 
      aria-label={`View profile of ${mentor.name || mentor.username}`}
    >
      <div className="card-top">
        <div className="avatar">{initials()}</div>
        <div className={`avail-badge avail-${mentor.availabilityStatus.toLowerCase()}`}>
          <span className="dot"></span>{mentor.availabilityStatus}
        </div>
      </div>

      <div className="card-body">
        <h3 className="mentor-name">{mentor.name || mentor.username}</h3>
        <p className="specialization">{mentor.specialization}</p>
        <p className="experience">{mentor.yearsOfExperience} years of experience</p>

        <div className="stats">
          <div className="stat">
            <span className="material-icons stat-icon">star</span>
            <span className="stat-val">
              {Number(finalRating).toFixed(1)}
            </span>
          </div>
          <div className="stat">
            <span className="material-icons stat-icon">reviews</span>
            <span className="stat-val">{finalReviews}</span>
          </div>
          <div className="stat">
            <span className="material-icons stat-icon">payments</span>
            <span className="stat-val">₹{mentor.hourlyRate}/hr</span>
          </div>
        </div>
      </div>

      <div className="card-actions">
        {isOwnProfile ? (
          <button 
            className="btn-manage" 
            onClick={(e) => { e.stopPropagation(); onView(mentor.userId); }}
          >
            <span className="material-icons">settings</span> Manage Profile
          </button>
        ) : (
          <div className="mentor-actions-row">
            <button 
              className="btn-book"
              onClick={(e) => { e.stopPropagation(); onBook(mentor.userId); }}
              disabled={mentor.availabilityStatus !== 'AVAILABLE'}
            >
              Book Session
            </button>
            <button 
              className="btn-view" 
              onClick={(e) => { e.stopPropagation(); onView(mentor.userId); }} 
            >
              View
            </button>
            <button 
              className="btn-chat-icon" 
              onClick={(e) => { e.stopPropagation(); onChat && onChat(mentor.userId); }}
            >
              <span className="material-icons text-white">chat</span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

// frontend/src/app/features/mentors/components/mentor-card/mentor-card.component.ts
import { Component, Input, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MentorProfileDto } from '../../../../shared/models';
import { AuthStore } from '../../../../core/auth/auth.store';
import { MessagingService } from '../../../../core/services/messaging.service';
import { ReviewService } from '../../../../core/services/review.service';
import { OnInit, signal } from '@angular/core';

@Component({
  selector: 'app-mentor-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './mentor-card.component.html',
  styleUrl: './mentor-card.component.scss'
})
export class MentorCardComponent implements OnInit {
  @Input({ required: true }) mentor!: MentorProfileDto;
  @Input() overrideRating?: number; // Pass loaded rating for current user
  @Input() overrideLearnersCount?: number; // Pass learners count for current user
  @Output() view = new EventEmitter<number>();
  @Output() book = new EventEmitter<number>();

  private readonly authStore = inject(AuthStore);
  private readonly messagingService = inject(MessagingService);
  private readonly reviewService = inject(ReviewService);

  readonly enrichedRating = signal<number | null>(null);
  readonly enrichedReviewCount = signal<number | null>(null);

  ngOnInit(): void {
    // Enrich card with real-time rating and review count from review-service
    this.reviewService.getMentorRating(this.mentor.userId).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          this.enrichedRating.set(res.data.averageRating);
          this.enrichedReviewCount.set(res.data.totalReviews);
        }
      },
      error: (err) => console.warn(`Failed to enrich ratings for mentor ${this.mentor.id}`, err)
    });
  }

  openChat(): void {
    const name = this.mentor.user?.name || this.mentor.user?.username || 'Mentor';
    this.messagingService.openPrivateChat(this.mentor.userId, name);
  }

  // Use method instead of computed() — @Input is not available at computed() init time
  isOwnProfile(): boolean {
    const myId = this.authStore.userId();
    return myId !== null && Number(myId) === Number(this.mentor.userId);
  }

  initials(): string {
    const name = this.mentor.name || this.mentor.username || this.mentor.specialization || '?';
    return name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase();
  }
}

<div class="card" (click)="view.emit(mentor.userId)" (keyup.enter)="view.emit(mentor.userId)" tabindex="0" role="button" [attr.aria-label]="'View profile of ' + (mentor.name || mentor.username)">
  <div class="card-top">
    <div class="avatar">{{ initials() }}</div>
    <div class="avail-badge" [class]="'avail-' + mentor.availabilityStatus.toLowerCase()">
      <span class="dot"></span>{{ mentor.availabilityStatus }}
    </div>
  </div>

  <div class="card-body">
    <h3 class="mentor-name">{{ mentor.name || mentor.username }}</h3>
    <p class="specialization">{{ mentor.specialization }}</p>
    <p class="experience">{{ mentor.yearsOfExperience }} years of experience</p>

    <div class="stats">
      <div class="stat">
        <span class="material-icons stat-icon">star</span>
        <span class="stat-val">
          {{ (enrichedRating() !== null ? enrichedRating() : (overrideRating !== undefined ? overrideRating : mentor.rating)) | number:'1.1-1' }}
        </span>
      </div>
      <div class="stat">
        <span class="material-icons stat-icon">reviews</span>
        <span class="stat-val">
          {{ enrichedReviewCount() !== null ? enrichedReviewCount() : (overrideLearnersCount !== undefined ? overrideLearnersCount : mentor.totalStudents) }}
        </span>
      </div>
      <div class="stat">
        <span class="material-icons stat-icon">payments</span>
        <span class="stat-val">₹{{ mentor.hourlyRate }}/hr</span>
      </div>
    </div>
  </div>

  <div class="card-actions">
    @if (isOwnProfile()) {
      <!-- Own profile: single full-width manage button -->
      <button class="btn-manage" (click)="$event.stopPropagation(); view.emit(mentor.userId)">
        <span class="material-icons">settings</span> Manage Profile
      </button>
    } @else {
      <!-- Other mentor: book + view -->
      <button class="btn-book"
              (click)="$event.stopPropagation(); book.emit(mentor.userId)"
              [disabled]="mentor.availabilityStatus !== 'AVAILABLE'">
        Book Session
      </button>
      <button class="btn-view" (click)="$event.stopPropagation(); view.emit(mentor.userId)" title="View Profile">
        View
      </button>
      <button class="btn-chat" (click)="$event.stopPropagation(); openChat()" title="Send Message">
        <span class="material-icons">chat</span>
      </button>
    }
  </div>
</div>
