// frontend-react/src/components/common/OtpInput.tsx
import React, { useRef, useState } from 'react';

interface OtpInputProps {
  onOtpComplete: (otp: string) => void;
}

export const OtpInput: React.FC<OtpInputProps> = ({ onOtpComplete }) => {
  const [digits, setDigits] = useState(['', '', '', '', '', '']);
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  const onInput = (e: React.ChangeEvent<HTMLInputElement>, index: number) => {
    const val = e.target.value.replace(/\D/g, '');
    const updated = [...digits];
    updated[index] = val.slice(-1);
    setDigits(updated);

    if (val && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }

    const otp = updated.join('');
    if (otp.length === 6) {
      onOtpComplete(otp);
    }
  };

  const onKeydown = (e: React.KeyboardEvent<HTMLInputElement>, index: number) => {
    if (e.key === 'Backspace' && !digits[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const onPaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    const pasted = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6);
    if (pasted.length === 6) {
      const split = pasted.split('');
      setDigits(split);
      onOtpComplete(pasted);
    }
    e.preventDefault();
  };

  return (
    <div className="flex gap-2 justify-center mb-6">
      {[0, 1, 2, 3, 4, 5].map((index) => (
        <input
          key={index}
          ref={(el) => { inputRefs.current[index] = el; }}
          type="text"
          maxLength={1}
          value={digits[index]}
          onChange={(e) => onInput(e, index)}
          onKeyDown={(e) => onKeydown(e, index)}
          onPaste={onPaste}
          className="w-12 h-14 text-center text-xl font-bold bg-slate-50 border border-slate-200 rounded-xl focus:border-primary-500 focus:ring-4 focus:ring-primary-500/10 outline-none transition-all dark:bg-slate-800 dark:border-slate-700 dark:text-white"
        />
      ))}
    </div>
  );
};

// frontend/src/app/features/auth/components/otp-input/otp-input.component.ts
import { Component, Output, EventEmitter, signal, ViewChildren, QueryList, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-otp-input',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="otp-wrapper">
      @for (i of indices; track i) {
        <input #otpInput class="otp-box" type="text" maxlength="1" inputmode="numeric"
          [value]="digits()[i]"
          (input)="onInput($event, i)"
          (keydown)="onKeydown($event, i)"
          (paste)="onPaste($event)" />
      }
    </div>
  `,
  styles: [`
    .otp-wrapper { display: flex; gap: 10px; justify-content: center; }
    .otp-box {
      width: 48px; height: 56px; text-align: center;
      font-size: 22px; font-weight: 600;
      border: 2px solid #e0e0e0; border-radius: 8px;
      outline: none; transition: border-color 0.2s;
    }
    .otp-box:focus { border-color: #5c6bc0; }
  `]
})
export class OtpInputComponent {
  @Output() otpComplete = new EventEmitter<string>();
  @ViewChildren('otpInput') inputs!: QueryList<ElementRef<HTMLInputElement>>;

  readonly indices = [0, 1, 2, 3, 4, 5];
  readonly digits = signal<string[]>(['', '', '', '', '', '']);

  onInput(event: Event, index: number): void {
    const val = (event.target as HTMLInputElement).value.replace(/\D/g, '');
    const updated = [...this.digits()];
    updated[index] = val.slice(-1);
    this.digits.set(updated);
    if (val && index < 5) this.inputs.toArray()[index + 1].nativeElement.focus();
    const otp = updated.join('');
    if (otp.length === 6) this.otpComplete.emit(otp);
  }

  onKeydown(event: KeyboardEvent, index: number): void {
    if (event.key === 'Backspace' && !this.digits()[index] && index > 0)
      this.inputs.toArray()[index - 1].nativeElement.focus();
  }

  onPaste(event: ClipboardEvent): void {
    const pasted = event.clipboardData?.getData('text').replace(/\D/g, '').slice(0, 6) ?? '';
    if (pasted.length === 6) { this.digits.set(pasted.split('')); this.otpComplete.emit(pasted); }
    event.preventDefault();
  }
}

<div class="otp-wrapper">
  @for (i of indices; track i) {
    <input #otpInput class="otp-box" type="text" maxlength="1" inputmode="numeric"
      [value]="digits()[i]"
      (input)="onInput($event, i)"
      (keydown)="onKeydown($event, i)"
      (paste)="onPaste($event)" />
  }
</div>
